Import upstream version 0.svn20080408

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25,27 +25,23 @@ exit 1
 fi
 
 cc_check() {
-    rm -f conftest*
     cat > conftest.c << EOF
 #include <$1>
 int main () { $3 return 0; }
 EOF
     $CC conftest.c $CFLAGS $LDFLAGS $2 -o conftest 2>$DEVNULL
     TMP="$?"
-    rm -f conftest*
     return $TMP
 }
 
 as_check() {
-    rm -f conftest*
     echo "$1" > conftest.asm
     $AS conftest.asm $ASFLAGS $2 -o conftest.o 2>$DEVNULL
     TMP="$?"
-    rm -f conftest*
     return $TMP
 }
 
-rm -f config.h config.mak x264.pc
+rm -f config.h config.mak x264.pc conftest*
 
 prefix='/usr/local'
 exec_prefix='${prefix}'
@@ -213,7 +209,7 @@ case $host_os in
     LDFLAGS="$LDFLAGS -lm"
     ;;
   cygwin*)
-    SYS="CYGWIN"
+    SYS="MINGW"
     CFLAGS="$CFLAGS -mno-cygwin"
     LDFLAGS="$LDFLAGS -mno-cygwin"
     EXE=".exe"
@@ -243,7 +239,7 @@ case $host_cpu in
     ASFLAGS="-O2"
     if [ "$SYS" = MACOSX ]; then
       ASFLAGS="$ASFLAGS -f macho -DPREFIX"
-    elif [ "$SYS" = CYGWIN -o "$SYS" = MINGW ]; then
+    elif [ "$SYS" = MINGW ]; then
       ASFLAGS="$ASFLAGS -f win32 -DPREFIX"
     elif [ "$SYS" = NETBSD ]; then
       ASFLAGS="$ASFLAGS -f aoutb"
@@ -320,6 +316,11 @@ then
 fi
 
 if [ $ARCH = X86 -o $ARCH = X86_64 ] ; then
+    if [ $ARCH = X86 -a $pic = yes -a x$AS = xyasm -a\
+         "`yasm --version | head -n 1`" "<" "yasm 0.6.2" ] ; then
+         echo "yasm prior to 0.6.2 miscompiles PIC. trying nasm instead..."
+         AS=nasm
+    fi
     if as_check ; then
         CFLAGS="$CFLAGS -DHAVE_MMX"
         if as_check "pabsw xmm0, xmm0" ; then
@@ -335,6 +336,10 @@ fi
 
 CFLAGS="$CFLAGS -DARCH_$ARCH -DSYS_$SYS"
 
+echo "unsigned int endian = 'B' << 24 | 'I' << 16 | 'G' << 8 | 'E';" > conftest.c
+$CC $CFLAGS conftest.c -c -o conftest.o 2>$DEVNULL || die "endian test failed"
+grep -q BIGE conftest.o && CFLAGS="$CFLAGS -DWORDS_BIGENDIAN"
+
 # autodetect options that weren't forced nor disabled
 
 libpthread=""
@@ -344,7 +349,7 @@ if test "$pthread" = "auto" ; then
         BEOS)
             pthread="yes"
             ;;
-        MINGW|CYGWIN)
+        MINGW)
             if cc_check pthread.h -lpthread "pthread_create(0,0,0,0);" ; then
                 pthread="yes"
                 libpthread="-lpthread"
@@ -368,7 +373,7 @@ if test "$pthread" = "yes" ; then
 fi
 
 MP4_LDFLAGS="-lgpac_static"
-if [ $SYS = CYGWIN -o $SYS = MINGW ]; then
+if [ $SYS = MINGW ]; then
     MP4_LDFLAGS="$MP4_LDFLAGS -lwinmm"
 fi
 if [ "$mp4_output" = "auto" ] ; then
@@ -381,7 +386,7 @@ if [ "$mp4_output" = "yes" ] ; then
 fi
 
 if [ "$avis_input" = "auto" ] ; then
-    if [ $SYS = CYGWIN -o $SYS = MINGW ]; then
+    if [ $SYS = MINGW ]; then
         avis_input="yes"
     else
         avis_input="no";
@@ -418,6 +423,8 @@ elif cc_check "stdio.h" "" "fseeko64(stdin,0,0);" ; then
     echo "#define ftell ftello64" >> config.h
 fi
 
+rm -f conftest*
+
 # generate config files
 
 cat > config.mak << EOF
@@ -452,7 +459,17 @@ cp config.mak gtk/config.mak
 
 if [ "$shared" = "yes" ]; then
     API=$(grep '#define X264_BUILD' < x264.h | cut -f 3 -d ' ')
-    echo "SONAME=libx264.so.$API" >> config.mak
+    if [ "$SYS" = "MINGW" ]; then
+        echo "SONAME=libx264-$API.dll" >> config.mak
+        echo 'IMPLIBNAME=libx264.dll.a' >> config.mak
+        echo 'SOFLAGS=-Wl,--out-implib,$(IMPLIBNAME) -Wl,--enable-auto-image-base' >> config.mak
+    elif [ "$SYS" = "MACOSX" ]; then
+        echo "SONAME=libx264.$API.dylib" >> config.mak
+        echo 'SOFLAGS=-dynamiclib -Wl,-single_module -Wl,-read_only_relocs,suppress' >> config.mak        
+    else
+        echo "SONAME=libx264.so.$API" >> config.mak
+        echo 'SOFLAGS=-Wl,-soname,$(SONAME)' >> config.mak
+    fi
     echo 'default: $(SONAME)' >> config.mak
     if [ "$gtk" = "yes" ]; then
         echo "SONAMEGTK=libx264gtk.so.$API" >> gtk/config.mak
